version: 2.1

jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:MerXeLmIk662ZRepQU4FbpEC5tvnU7jx1Yt4cV2B17k" # Use the actual fingerprint of your EC2 SSH key
            - "SHA256:gvDudu58T2BodjaGSREXbstbfLWGvy92w+4JprJOdiY" # Fingerprint del colaborador
      - run:
          name: SSH and Pull Latest Code
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@ec2-52-201-18-119.compute-1.amazonaws.com "cd ~/gpsGit && git pull origin master"
      - run:
          name: SSH and Pull Latest Code - Collaborator
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@54.211.70.225 "cd ~/gpsGit && git pull origin master"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
